import Head from 'next/head'
import AmazingHeader from '../components/AmazingHeader/AmazingHeader'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <AmazingHeader />
    </div>
  )
}
// /smartphones
// /smartphones/123
